export const BCBANK_USER__TYPE_PERSONAL = 0;
export const BCBANK_USER__TYPE_CORPORATE = 1;

export const BCBANK_USER_PASSWORD_VALIDATION_ERROR_CODE__TOO_SHORT = 0;
export const BCBANK_USER_PASSWORD_VALIDATION_ERROR_CODE__TOO_LONG = 1;
export const BCBANK_USER_PASSWORD_VALIDATION_ERROR_CODE__TOO_SIMILAR_EMAIL = 2;
export const BCBANK_USER_PASSWORD_VALIDATION_ERROR_CODE__TOO_COMMON = 3;
export const BCBANK_USER_PASSWORD_VALIDATION_ERROR_CODE__ENTIRELY_NUMERIC = 4;
export const BCBANK_USER_PASSWORD_VALIDATION_ERROR_CODE__NO_NUMBER = 5;
export const BCBANK_USER_PASSWORD_VALIDATION_ERROR_CODE__CONTAIN_SEQUENTIAL = 6;
